Update variables to not potentially conflict with other ansible roles or playbooks.
jeffwidman/ansible-yum-cron pull request #9
Opened 2020-02-10 00:11 UTC by Red-M

As per the title, this is so that the variable names in this role are not able to conflict with other roles or playbooks by introducing a prefix to the variable names used.

2020-02-10 07:22 UTC, martbhell requested changes
This is so good. Thanks! 
Unfortunately no CI configured in this repo so took me a bit more work for me to check it out.
But at least no syntax errors :)


there's an "emit_via" still in there. After changing that to yum_cron_emit_via then ansible could proceed.

2020-02-10 07:28 UTC, Red-M commented
Should be fixed now.

2020-02-10 07:33 UTC, martbhell approved these changes

2020-02-10 07:34 UTC, merged

2020-02-10 07:35 UTC, martbhell commented
Seems so. 

Ran it with --diff and --check on my laptop with some minor modifications to just the task.yml and at least the resulting config file looks sane to me.

2020-02-11 18:01 UTC, jeffwidman commented
👍